\LoadClass[10pt,a4paper]{letter}

%Use \documentstyle[newcent]{letter} for New Century Schoolbook postscript font
% the following commands control the margins:
\topmargin=-1in    % Make letterhead start about 1 inch from top of page 
\textheight=8in    % text height can be bigger for a longer letter
\oddsidemargin=0pt % leftmargin is 1 inch
\textwidth=6.5in   % textwidth of 6.5in leaves 1 inch for right margin

\longindentation=0pt % needed to get closing flush left

\let\raggedleft\raggedright % needed to get date flush left\begin{flushleft}


\signature{\YourName\\
Corresponding Author\\
\YourTitle\\
\InstitutionName\\
\InstitutionAddress\\
\YourEmail} % name for signature 